### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by SoroushK93** [DEAkimov/learn_to_move#2]
Hi

Thank you for the codes and congrats on your great work and results.
when I run main.py, I get the following error:
FileNotFoundError: [Errno 2] No such file or directory: 'src/experiments/exp_8c_2.json'
how can I have this file? 
should I train the model on my own? if yes, do we have access to the training file?

Many thanks and best regards

**Comment by CherryPieSexy** [comment]
Hi!
Sorry for delayed response, for some reason I didn't get notification on this issue.

I have this config for training on my laptop and will add it to the repository soon.
If you interested in trained models I can add them too.

**Comment by SoroushK93** [comment]
Hi!
Thanks for your reply.
Yes, I would be thankful if you could add the config and models.

**Comment by CherryPieSexy** [comment]
Ok, I will test trained models and add them along with the config tomorrow.
However, I am not sure if you will be able to reproduce my results, because the code changed several times during experiments and final model checkpoints were loaded between experiments.

**Comment by CherryPieSexy** [comment]
Hi!
I added missing config and models checkpoints along with test script in 'models' folder. I tested it on my laptop and it works fine. Let me know if it won't work on your machine.

**Comment by SoroushK93** [comment]
Thank you very much. I really appreciate it. I could run the program! 
I get an error that seems is related to the ram/GPU of my windows!
OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading ...lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies

**Comment by CherryPieSexy** [comment]
Yes, it seems like a library installation problems. Which script did you run? I suggest to try models/test_models.py first to see working model.

**Comment by SoroushK93** [comment]
Thank you very much. I get the following error when I run the models/test_model.py. It seems it is relevant to the packages. I spent a lot of time on it, but, I didn't find a good solution on the web.

  File "C:\Users\username\Anaconda3\envs\opensim-rl\lib\site-packages\torch\serialization.py", line 307, in raise_err_msg
    raise type(e)(msg)
AttributeError: 'NoneType' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.

**Comment by CherryPieSexy** [comment]
I think it is because you have to provide path to model checkpoint to run this script. Look at the code (from test_models.py script):
```
    parser.add_argument(
        '--model_name', '-p',
        help='name of file with model checkpoint to load.',
        type=str
    )
```

**Comment by SoroushK93** [comment]
I'm really thankful for your time and consideration. I think your explanation is very clear, but because I'm a starter I cannot implement what you just explained. If you could help me with the implementation that would be really great.
I just used epoch_39 (the latest saved checkpoint) instead of the model_name in the model_test.py
one more time, I used the complete path (r'C:\Users\username\Anaconda3\envs\opensim-rl\learn_to_move\models\epoch_39.pth') but I couldn't still run it.


 def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        '--model_name', '-p',
        help='name of file with model checkpoint to load.',
        type=str
    )
    parser.add_argument(
        '--n_episodes', '-n',
        help='number of episodes to play, default 3.',
        default=3, type=int
    )
    return parser.parse_args()


def main():
    args = parse_args()
    model = PolicyNet((11 * 11 * 2, 97), 1024, 22)
    print(args.epoch_39.pth)
    checkpoint = torch.load(args.epoch_39.pth, map_location='cpu')
    policy_checkpoint = checkpoint['policy_net']
    model.load_state_dict(policy_checkpoint)
    model.eval()

    env = L2M2019Env(integrator_accuracy=1e-3)
    for _ in range(args.n_episodes):
        play_ep(env, model)
    env.close()

**Comment by CherryPieSexy** [comment]
Hopefully `checkpoint = torch.load('epoch_39.pth', map_location='cpu')` will work.

**Comment by SoroushK93** [comment]
Thank you very much. It works fine now. I really appreciate it.

**Comment by CherryPieSexy** [comment]
I am very glad that it works :)
